app:
  kafka:
    topic: Device

logging:
  level:
    root: INFO
    ch.raphaelbrunner: DEBUG

server:
  port: 6969

spring:
  application:
    name: device-discovery-service
  kafka:
    client-id: device-discovery-service
    producer:
      bootstrap-servers:
        - localhost:9092