app:
  kafka:
    topic: Action

logging:
  level:
    root: INFO
    ch.raphaelbrunner: DEBUG

server:
  port: 6971

spring:
  application:
    name: action-executor
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  kafka:
    client-id: action-executor
    consumer:
      bootstrap-servers:
        - localhost:9092
      isolation-level: read_committed
      group-id: action-executor